version: '2'
services:
  db:
    container_name: ndb
    build: ./db
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'codeignitertest'
    volumes:
      - ./db/mysql_data:/var/lib/mysql
  web:
    container_name: nweb
    build: ./web
    restart: always
    ports:
      - '8080:80'
    depends_on:
      - db
    tty: true
  cache:
    container_name: nredis
    build: ./web
    restart: always
    volumes:
      - ./cache:/data
    ports:
      - '6379:6379'
    command: redis-server --appendonly yes
